services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: artdict_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/database:ro

volumes:
  postgres_data:
